name: Continuous master build

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .venv/
          key: virtualenv
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.13"
      - name: Run linters
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-root
          poetry run black --check .
          poetry run mypy .

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .venv/
          key: virtualenv
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10.4"
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.1.13"
      - name: Build artifacts
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-dev
          poetry build
      - name: Rename artifacts
        run: |
          mv dist/1p-*.whl dist/1p-tip-py3-none-any.whl
          mv dist/1p-*.tar.gz dist/1p-tip.tar.gz
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: 1p-tip
          path: |
            dist/1p-tip-py3-none-any.whl
            dist/1p-tip.tar.gz

  package:
    runs-on: ubuntu-20.04
    needs: [lint, build]
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist/
      - name: Create release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: tip
          title: Development build
          prerelease: true
          files: dist/1p-tip/*


